apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  # type: NodePort when i deploy locally, i use NodePort
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
      # nodePort: 31001 # Uncomment this line when deploying locally
      name: result-service-port
  selector:
    app: result