apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  # type: NodePort when I deploy locally, I use NodePort
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      # nodePort: 31000 # Uncomment this line when deploying locally
      name: vote-service-port
  selector:
    app: vote