apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31001
      name: result-service-port
  selector:
    app: result